package pinnacle.api.enums;

public enum PLACEBET_ERROR_CODE {

	ALL_BETTING_CLOSED,
	ALL_LIVE_BETTING_CLOSED,
	ABOVE_EVENT_MAX,
	ABOVE_MAX_BET_AMOUNT,
	BELOW_MIN_BET_AMOUNT,
	BLOCKED_BETTING,
	BLOCKED_CLIENT,
	INSUFFICIENT_FUNDS,
	INVALID_COUNTRY,
	INVALID_EVENT,
	INVALID_ODDS_FORMAT,
	LINE_CHANGED,
	LISTED_PITCHERS_SELECTION_ERROR,
	OFFLINE_EVENT,
	PAST_CUTOFFTIME,
	RED_CARDS_CHANGED,
	SCORE_CHANGED,
	TIME_RESTRICTION,
	UNDEFINED;

	public String toAPI () {
		return this.name();
	}
	
	public static PLACEBET_ERROR_CODE fromAPI (String text) {
		try {
			return PLACEBET_ERROR_CODE.valueOf(text);
		} catch (IllegalArgumentException e) {
			return PLACEBET_ERROR_CODE.UNDEFINED;
		}
	}
}
