package pinnacle.api.enums;

public enum PLACE_TEASER_BET_ERROR_CODE {

	ABOVE_MAX_BET_AMOUNT,
	ALL_BETTING_CLOSED,
	BELOW_MIN_BET_AMOUNT,
	BLOCKED_BETTING,
	BLOCKED_CLIENT,
	DOUBLE_HIT,
	DUPLICATE_CLIENT_REFERENCE_ID,
	INCOMPLETE_CUSTOMER_BETTING_PROFILE,
	INSUFFICIENT_FUNDS,
	INVALID_COUNTRY,
	INVALID_CUSTOMER_PROFILE,
	INVALID_LEGS,
	INVALID_REQUEST,
	ODDS_FORMAT_MISMATCH,
	RESUBMIT_REQUEST,
	TEASER_DOES_NOT_EXIST,
	SAME_EVENT_ONLY_REQUIRED,
	SYSTEM_ERROR_1,
	SYSTEM_ERROR_2,
	SYSTEM_ERROR_3,
	TOO_FEW_LEGS,
	TOO_MANY_LEGS,
	UNKNOWN,
	WAGERING_SUSPENDED,
	UNDEFINED;

	public String toAPI () {
		return this.name();
	}
	
	public static PLACE_TEASER_BET_ERROR_CODE fromAPI (String text) {
		try {
			return PLACE_TEASER_BET_ERROR_CODE.valueOf(text);
		} catch (IllegalArgumentException e) {
			return PLACE_TEASER_BET_ERROR_CODE.UNDEFINED;
		}
	}
}
